from datetime import datetime
from typing import Protocol, runtime_checkable

from app.domain.models import Certification


@runtime_checkable
class ContentRepository(Protocol):
    async def save_certification(self, cert: Certification) -> None: ...
    async def load_certification(self, cert_id: str) -> Certification | None: ...
    async def has_certification(self, cert_id: str) -> bool: ...
    async def get_last_scraped(self, cert_id: str) -> datetime | None: ...
